remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Daneul Kim
description: [Curriculum Vitae](https://drive.google.com/file/d/1p5xkXNV_j_u9ciM4kGcv90zfCxtNA2ur/view?usp=sharing)
logo: image.jpg
